apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: web-pod
    image: nginx
    volumeMounts:
    - mountPath: "/tmp/www/html"
      name: web-volume-01
  volumes:
  - name: web-volume-01
    persistentVolumeClaim:
      claimName: claim-01

