apiVersion: v1
kind: Pod
metadata:
  name: web-storage
spec:
  containers:
  - name: web-storage
    image: nginx
    volumeMounts:
    - mountPath: "/tmp/www/html"
      name: web-volume-01
  volumes:
  - name: web-volume-01
    persistentVolumeClaim:
      claimName: storage-pvc

