apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers: 
  - name: nginx
    image: nginx
    volumeMounts: 
    - mountPath: /logs
      name: logs-vol 
  volumes: 
  - name: logs-vol
    hostPath: 
     path: /var/logs/webapp

