---
apiVersion: v1
kind: Namespace
metadata:
  name: hr

---
apiVersion: v1
kind: Pod
metadata:
  name: hr-pod
  namespace: hr
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["sleep"]
    args: ["7"]

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-quota
  namespace: hr
spec:
  hard:
    pods: "2"
