---
apiVersion: v1
kind: Namespace
metadata:
  name: finance

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: finance
spec:
  replicas: 4
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      namespace: finance
      labels:
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
