---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
data:
  DB_Host: ZGItdXNlcjAxCg==
  DB_User: YWRtaW4wMQo= 
  DB_Password: RWswU2tsOTFwcwo=

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx
    env:
    - name: DB_Host
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_Host
    - name: DB_User
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_User
    - name: DB_Password
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_Password      
