apiVersion: v1
kind: Pod
metadata:
  name: multi-secret-pod
spec: 
  containers: 
  - name: multi-secret-pod
    image: nginx 
    env: 
     -  name: DB_Admin 
        valueFrom:  
          secretKeyRef: 
            name: credentials-secret
            key: DB_Admin
     -  name: DB_Password 
        valueFrom: 
          secretKeyRef: 
            name: db-secret
            key: DB_Password

