apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-challenge
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: nginx-deployment-challenge
        image: nginx:1.17.0
