apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-1
spec:
   replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:1.18.0
