---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-1
  labels:
   env: webapp-1
spec:
  containers:
  - name: webapp-1 
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
spec:
  selector:
    env: webapp-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

