apiVersion: v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
spec:
   replicas: 4
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: redis-replicaset
        image: redis
