---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgcolorapp
  labels:
    env: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      env: front-end
  template:
    metadata:
      labels:
        env: front-end
    spec:
      containers:
      - name: bgcolorapp
        image: chtan2019/kubernetes101
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bgcolorapp
spec:
  type: NodePort
  selector:
    env: front-end
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
