apiVersion: v1
kind: Pod
metadata:
  name: multi-configmap-pod
spec:
  containers: 
  - name: configmap-pod
    image: nginx
    env: 
    - name: color
      valueFrom: 
        configMapKeyRef: 
          name: color-configmap-2 
          key: APP_COLOR
    - name: demo_greeting
      valueFrom: 
        configMapKeyRef: 
          name: color-configmap-1
          key: demo_greeting

